Dot product between two vectors

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.dot(a,b)

32

Below gives geometric length of the vector

In [3]:
np.linalg.norm(a)

3.7416573867739413

Cauchy-Schwarz inequality

In [5]:
np.dot(a,b) / (np.linalg.norm(a)*np.linalg.norm(b))

0.9746318461970762

In [7]:
np.dot(a,a) == (np.linalg.norm(a)) ** 2

True

Matrix-Vector product

In [13]:
#here A is weights matrix
A = np.array([[1,2,-1,-1], [2,4,-2,3], [-1,1,-2,4]])
print(A)
print(A.shape)

#so matrix stored row-wise in memory
print(A[0])
print(A[1])
print(A[2])


print(A[0].shape)

[[ 1  2 -1 -1]
 [ 2  4 -2  3]
 [-1  1 -2  4]]
(3, 4)
[ 1  2 -1 -1]
[ 2  4 -2  3]
[-1  1 -2  4]
(4,)


In [50]:
x = np.array([-1,1,1,0])

In [18]:
#matrix vector product
#In GPU calculations happen in parallel

print(np.dot(A,x))

[0 0 0]


Tensors

In [20]:
T = np.array([[[74, 128], [79, 116], [71, 116]],
             [[78, 118], [82, 124], [72, 128]],
             [[84, 138], [84, 130], [74, 120]],
             [[82, 126], [76, 156], [82, 132]]])

print(T)
print(T.shape)

[[[ 74 128]
  [ 79 116]
  [ 71 116]]

 [[ 78 118]
  [ 82 124]
  [ 72 128]]

 [[ 84 138]
  [ 84 130]
  [ 74 120]]

 [[ 82 126]
  [ 76 156]
  [ 82 132]]]
(4, 3, 2)


In [21]:
print(T[0])

[[ 74 128]
 [ 79 116]
 [ 71 116]]


In [22]:
print(T[0][0])

[ 74 128]


In [46]:
#cook up a vector x to do dot product with tensor T
x =  np.array([1,0])
print(x.shape)

np.dot(T,x)

(2,)


array([[74, 79, 71],
       [78, 82, 72],
       [84, 84, 74],
       [82, 76, 82]])

In [47]:
T.reshape(3,2,4)

array([[[ 74, 128,  79, 116],
        [ 71, 116,  78, 118]],

       [[ 82, 124,  72, 128],
        [ 84, 138,  84, 130]],

       [[ 74, 120,  82, 126],
        [ 76, 156,  82, 132]]])

In [61]:
A

array([[ 1,  2, -1, -1],
       [ 2,  4, -2,  3],
       [-1,  1, -2,  4]])

In [62]:
x

array([-1,  1,  1,  0])

In [63]:
#Linear Combination
x[0] * A[:,0] + x[1] * A[:,1] + x[2] * A[:,2] + x[3] * A[:,3]

array([0, 0, 0])

In [73]:
#better way to do above
np.sum(x[range(4)] * A[:,range(4)])

0