In [2]:
## Load Libraries
import pandas as pd
import numpy as np
import sympy as sp
import matplotlib.pyplot as plt
%matplotlib inline

---

Dot product between two vectors is simply a pairwise-multiplication followed by a summation: for example, $a\cdot b = a_1\times b_2+a_2\times b_2+\cdots+a_n\times b_n.$

---

In [3]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.dot(a, b)

32

---

$L_2$ norm or the geometric length of a vector denoted as $\lVert a\rVert$ tells us how long a vector is. In 2-dimensions, $\lVert a\rVert_2 = \sqrt{a_1^2+a_2^2}$ and in $n$-dimensions, $\lVert a\rVert_2 = \sqrt{a_1^2+a_2^2+\cdots+a_n^2}.$

---

In [4]:
np.linalg.norm(a)

3.7416573867739413

---

Cauchy-Schwarz inequality $-1\leq\frac{a\cdot b}{\lVert a\rVert\lVert b\rVert}\leq1.$

---

In [5]:
np.dot(a, b) / (np.linalg.norm(a)*np.linalg.norm(b))

0.9746318461970762

---

Matrix-vector product is simply a sequence of dot products of the rows of matrix (seen as vectors) with the vector

---

In [6]:
A = np.array([[1,2,-1,-1], [2,4,-2,3], [-1,1,-2,4]])
x = np.array([-1, 1, 1, 0])
print(A)
print(A.shape)
print(A[0])
print(A[1])
print(A[2])
print(A[0].shape)
print(x)
print(np.dot(A, x))

[[ 1  2 -1 -1]
 [ 2  4 -2  3]
 [-1  1 -2  4]]
(3, 4)
[ 1  2 -1 -1]
[ 2  4 -2  3]
[-1  1 -2  4]
(4,)
[-1  1  1  0]
[0 0 0]


---

A tensor of dimension 3 corresponding to 4 time stamps, 3 samples, 2 features (HR and BP)

---

In [7]:
# Create a tensor of dimesion 3
# 4 time stamps, 3 samples, 2 features
T = np.array([[[74, 128], [79, 116], [71, 116]],
              [[78, 118], [82, 124], [72, 128]],
              [[84, 138], [84, 130], [74, 120]],
              [[82, 126], [76, 156], [82, 132]]])
print(T.shape)
print(T)
print(T[0])
print(T[0][0])

(4, 3, 2)
[[[ 74 128]
  [ 79 116]
  [ 71 116]]

 [[ 78 118]
  [ 82 124]
  [ 72 128]]

 [[ 84 138]
  [ 84 130]
  [ 74 120]]

 [[ 82 126]
  [ 76 156]
  [ 82 132]]]
[[ 74 128]
 [ 79 116]
 [ 71 116]]
[ 74 128]


---

Reshape tensor to represent (patient, feature, timestamps). That is, the timestamp becomes the last index.

---

In [ ]:
T_reshaped = T.transpose(1, 0, 2)
print(T_reshaped)
print(T_reshaped[0])
print(T_reshaped[:, :, 1])

In [ ]:
print(T.transpose(1, 2, 0))

---

Tensor-vector product is simply a sequence of matrix-vector products which in turn are a sequence of dot products of vectors

---

In [ ]:
x = np.array([1, 0])
print(T)
print(x)
print(T.shape)
print(x.shape)
print(np.dot(T, x))

---

Linear combination of columns of the matrix using the components of the vector is equivalent to the dot product of the rows of the matrix with the vector

----

In [ ]:
print(A)
print(x)
# Dot product of rows of A with x
print(np.dot(A, x))
# Linear combination of columns of A using components of x
print(x[0]*A[:, 0] + x[1]*A[:, 1] + x[2]*A[:, 2] + x[3]*A[:, 3])
np.sum(x[range(4)] * A[:, range(4)], axis = 1) # faster



---


The $\texttt{sympy}$ library in Python is for symbolic computing. When using this library, everything including numbers are treated as symbols. This library can be used for calculating the RREF of an augmented matrix coming from a system of linear equations. Consider the system of linear equations $$\boxed{\begin{align*}x_1+2x_2-x_3-x_4&={\color{cyan}1},\\2x_1+4x_2-2x_3+3x_4&={\color{cyan}3},\\-x_1+x_2-2x_3+4x_4&={\color{cyan}2}.\end{align*}}$$
Note the folowing equivalent ways of interpreting this system of equations:
$$\boxed{\begin{align*}\underbrace{\begin{bmatrix}
1 &2 & -1 & -1  \\
2 & 4 & -2 & 3  \\
-1 & 1 & -2 & 4   
\end{bmatrix}}_{A}\underbrace{\begin{bmatrix}x_1\\x_2\\x_3\\x_4\end{bmatrix}}_{x}&=\underbrace{\begin{bmatrix}{\color{cyan}1}\\{\color{cyan}3}\\{\color{cyan}2}\end{bmatrix}}_{\color{cyan}b}\end{align*}}\Longleftrightarrow \underbrace{\boxed{x_1a_1+x_2a_2+x_3a_3+x_4a_4 = {\color{cyan}b}}}_{\color{green}{\text{linear combination of columns of }A}}\Longleftrightarrow \underbrace{\boxed{\begin{bmatrix}a^{(1)}\cdot x\\a^{(2)}\cdot x\\a^{(3)}\cdot x\end{bmatrix} =\begin{bmatrix}{\color{cyan}1}\\{\color{cyan}3}\\{\color{cyan}2}\end{bmatrix}}.}_{\color{green}{\text{Dot product of }x\text{ with rows of }A}}$$ The augmented matrix for this system of equations is $$\begin{align*}
\begin{bmatrix}
1 &2 & -1 & -1 &\lvert& {\color{cyan}1}\\
2 & 4 & -2 & 3 & \lvert&{\color{cyan}3}\\
-1 & 1 & -2 & 4 & \lvert&{\color{cyan}2}
\end{bmatrix}.
\end{align*}$$
The RREF of this augmented matrix can be calculated using the following Python code:

---

In [12]:
Ag = sp.Matrix([[1,2,0],[2,1,0]])
Ag.rref()

(Matrix([
 [1, 0, 0],
 [0, 1, 0]]),
 (0, 1))

In [15]:
Ag = sp.Matrix([[72,144,0],[76,152,0],[80,160,0]])
Ag.rref()

(Matrix([
 [1, 2, 0],
 [0, 0, 0],
 [0, 0, 0]]),
 (0,))

In [ ]:
# Augmented matrix
Ag = sp.Matrix([[-2,-1,1,0], [-1,3,1,0]])

# Return the RREF and the pivot column indices as a tuple
print(Ag.rref())

In [8]:
# Augmented matrix
Ag = sp.Matrix([[1,2,-1,-1,1], [2,4,-2,3,3], [-1,1,-2,4,2]])

# Return the RREF and the pivot column indices as a tuple
print(Ag.rref())

(Matrix([
[1, 0,  1, 0, -2/5],
[0, 1, -1, 0,  4/5],
[0, 0,  0, 1,  1/5]]), (0, 1, 3))


---

This shows that $x_1, x_2,$ and $x_4$ are pivot variables and that $x_3$ is the only free variable. This system is $\color{green}{consistent}$ with $\color{green}{infinitely\ many\ solutions}$ as we see from the RREF above that
$$x_1=-x_3-(2/5),\,x_2=x_3+(4/5),\,x_4=1/5,$$
where $x_3$ can be any (real) number. We can also express the solution in vector notation as follows:
\begin{align*}
x &= \begin{bmatrix}x_1\\x_2\\x_3\\x_4\end{bmatrix} = \begin{bmatrix}-x_3-\frac{2}{5}\\x_3+\frac{4}{5}\\x_3\\\frac{1}{5}\end{bmatrix} = \underbrace{x_3\begin{bmatrix}-1\\1\\1\\0\end{bmatrix}}_{\text{solution to }Ax=0}+\underbrace{\begin{bmatrix}-\frac{2}{5}\\\frac{4}{5}\\0\\\frac{1}{5}\end{bmatrix}}_{\text{particular solution}},
\end{align*}  
noting again that $x_3$ can be any (real) number. Note that the solution has two parts:

* the first one involving the free variable(s) is the solutions to $Ax = 0$ (called the null space solution);
* the next one is the particular solution to $Ax=b.$




---

In [10]:
A = np.array([[1,2,-1,-1], [2,4,-2,3], [-1,1,-2,4]])
x3 = 1
x = x3*np.array([-1, 1, 1, 0]) + np.array([-2/5, 4/5, 0, 1/5])

# Check null space solution (Ax = 0)
print(np.dot(A, x3*np.array([-1, 1, 1, 0])))

# Check particular solution (Ax = b)
print(np.dot(A, np.array([-2/5, 4/5, 0, 1/5])))

# Check full solution (Ax = b)
print(np.dot(A, x))

[0 0 0]
[1. 3. 2.]
[1. 3. 2.]


---

To check whether the columns of a matrix are ${\color{green}{linearly\ independent\ or\ dependent}},$ we use the $\color{cyan}{zero\ right\ hand\  side\ vector}.$ Picking up from the previous example the matrix $A,$ we want to find a vector $x$ such that $$Ax = \color{cyan}0$$ which is equivalent to finding a vector $x$ such that $$x_1a_1+x_2a_2+x_3a_3+x_4a_4 = \color{cyan}0.$$

If the only solution is $x=0,$ then we say that the columns of $A$ are ${\color{green}{linearly\ independent}}$; otherwise, we say that the columns are ${\color{green}{linearly\ dependent}}.$

Now we will check if the columns of the matrix $A = \begin{bmatrix}1&2\\2&1\end{bmatrix}$ are ${\color{green}{linearly\ independent\ or\ dependent}}.$

---

In [ ]:
# Augmented matrix
Ag = sp.Matrix([[1, 2, 0], [2, 1, 0]])

# Return the rref and the pivot column indices as a tuple
print(Ag.rref())

---

As the only possible solution is $x=0$ (the zero vector), which is indicated by the fact that all variables are ${\color{magenta}{pivot}},$ the columns of $A$ are ${\color{green}{linearly\ independent}}.$

---

---

Now we will check if the columns of the matrix $A = \begin{bmatrix}1&2&4\\2&1&5\end{bmatrix}$ are ${\color{green}{linearly\ independent\ or\ dependent}}.$

---

In [16]:
# Augmented matrix
Ag = sp.Matrix([[1, 2, 4, 0], [2, 1, 5, 0]])

# Return the rref and the pivot column indices as a tuple
print(Ag.rref())

(Matrix([
[1, 0, 2, 0],
[0, 1, 1, 0]]), (0, 1))


---

We see that $x_1,x_2$ are the ${\color{magenta}{pivot}}$ variables and $x_3$ is the ${\color{orange}{free}}$ variable resulting in the solution $$\boxed{\begin{align*}{\color{magenta}{x_1}}+2{\color{orange}{x_3}} &=0,\\{\color{magenta}{x_2}}+{\color{orange}{x_3}}&=0\end{align*}}\Rightarrow \boxed{\begin{align*}x&=\begin{bmatrix}{\color{magenta}{x_1}}\\{\color{magenta}{x_2}}\\{\color{orange}{x_3}}\end{bmatrix}=\begin{bmatrix}-2{\color{orange}{x_3}}\\-{\color{orange}{x_3}}\\{\color{orange}{x_3}}\end{bmatrix}={\color{orange}{x_3}}\begin{bmatrix}-2\\-1\\1\end{bmatrix},\end{align*}}$$where ${\color{orange}{x_3}}$ is any real number clearly showing the one degree of freedom in the solution to the system of equations $Ax = {\color{cyan}0}.$

---

---

Now we will check if the columns of the matrix $A = \begin{bmatrix}1&1&1&1\\1&2&3&4\\4&3&2&1\end{bmatrix}$ are ${\color{green}{linearly\ independent\ or\ dependent}}.$

---

In [17]:
# Augmented matrix
Ag = sp.Matrix([[1, 1, 1, 1, 0], [1, 2, 3, 4, 0], [4, 3, 2, 1, 0]])

# Return the rref and the pivot column indices as a tuple
print(Ag.rref())

(Matrix([
[1, 0, -1, -2, 0],
[0, 1,  2,  3, 0],
[0, 0,  0,  0, 0]]), (0, 1))


---

We see that $x_1,x_2$ are the ${\color{magenta}{pivot}}$ variables and $x_3, x_4$ are the ${\color{orange}{free}}$ variables resulting in the solution $$\boxed{\begin{align*}{\color{magenta}{x_1}}-{\color{orange}{x_3}}-2{\color{orange}{x_4}} &=0,\\{\color{magenta}{x_2}}+2{\color{orange}{x_3}}+3{\color{orange}{x_4}}&=0,\end{align*}}\Rightarrow \boxed{\begin{align*}x &=\begin{bmatrix}{\color{magenta}{x_1}}\\{\color{magenta}{x_2}}\\{\color{orange}{x_3}}\\{\color{orange}{x_4}}\end{bmatrix}=\begin{bmatrix}{\color{orange}{x_3}}+2{\color{orange}{x_4}}\\-2{\color{orange}{x_3}}-3{\color{orange}{x_4}}\\{\color{orange}{x_3}}\\{\color{orange}{x_4}}\end{bmatrix}={\color{orange}{x_3}}\begin{bmatrix}1\\-2\\1\\0\end{bmatrix}+{\color{orange}{x_4}}\begin{bmatrix}2\\-3\\0\\1\end{bmatrix},\end{align*}}$$where ${\color{orange}{x_3}}\text{ and } {\color{orange}{x_4}}$ are any real numbers clearly showing the two degrees of freedom in the solution to the system of equations $Ax = {\color{cyan}0}.$

We see that columns 1 and 2 correspond to the ${\color{magenta}{pivot}}$ positions where as columns 3 and 4 correspond to the ${\color{orange}{free}}$ positions.

We will now show that the columns corresponding to the ${\color{orange}{free}}$ positions can be written in terms of the columns corresponding to the ${\color{magenta}{pivot}}$ positions. We do this by first noting that the system of equations $Ax ={\color{cyan}0}$ is equivalent to the linear combination $${\color{magenta}{x_1a_1}}+{\color{magenta}{x_2a_2}}+{\color{orange}{x_3a_3}}+{\color{orange}{x_4a_4}} = {\color{cyan}0}.$$ Then, we choose ${\color{orange}{x_3}}=1$ and ${\color{orange}{x_4}} = 0$ to get the solution vector $$x=\begin{bmatrix}1\\-2\\1\\0\end{bmatrix}.$$ We use this in the equation above to get $$\boxed{{\color{magenta}{a_1}}-2{\color{magenta}{a_2}}+{\color{orange}{a_3}} = {\color{cyan}0} \Rightarrow {\color{orange}{a_3}} = -{\color{magenta}{a_1}}+2{\color{magenta}{a_2}}.}$$ Similarly, by choosing ${\color{orange}{x_3}}=0$ and ${\color{orange}{x_4}} = 1,$ we can get $$\boxed{2{\color{magenta}{a_1}}-3{\color{magenta}{a_2}}+{\color{orange}{a_4}} = {\color{cyan}0} \Rightarrow {\color{orange}{a_4}} = -2{\color{magenta}{a_1}}+3{\color{magenta}{a_2}}.}$$  

---



---


Under what condition on the vector ${\color{cyan}b}$ will the system $Ax= {\color{cyan}b}$ below will be consistent; that is, it has a solution?

$$\begin{align*}\begin{bmatrix}1&1&1&1\\1&2&3&4\\4&3&2&1\end{bmatrix}\begin{bmatrix}x_1\\x_2\\x_3\end{bmatrix} &= \begin{bmatrix}{\color{cyan}{b_1}}\\{\color{cyan}{b_2}}\\{\color{cyan}{b_3}}\end{bmatrix}?\end{align*}$$  

Try first with $b = \begin{bmatrix}{\color{cyan}{1}}\\{\color{cyan}{2}}\\{\color{cyan}{4}}\end{bmatrix}$ and then $b = \begin{bmatrix}{\color{cyan}{1}}\\{\color{cyan}{2}}\\{\color{cyan}{3}}\end{bmatrix}.$

---

In [ ]:
# Augmented matrix
Ag = sp.Matrix([[1, 1, 1, 1, 1], [1, 2, 3, 4, 2], [4, 3, 2, 1, 3]])

# Return the rref and the pivot column indices as a tuple
print(Ag.rref())

In [20]:
Ag = sp.Matrix([[1,4,7,10],[2,5,8,11],[3,6,9,12]])
print(Ag.rref())

(Matrix([
[1, 0, -1, -2],
[0, 1,  2,  3],
[0, 0,  0,  0]]), (0, 1))


---

When does a system of equations $\boxed{Ax = {\color{cyan}{b}}}$ have a solution; that is, consistent?

Consider the following coefficient matrix:

$$\begin{align*}A&=\begin{bmatrix}1&1&1&1\\1&2&3&4\\4&3&2&1\end{bmatrix}.\end{align*}$$

Keeping the right hand side vector ${\color{cyan}{b}}$ as symbolic, we get the following RREF through the elementary row operations:

$$\begin{align*}\begin{bmatrix}1&1&1&1&\lvert&{\color{cyan}{b_1}}\\1&2&3&4&\lvert&{\color{cyan}{b_2}}\\4&3&2&1&\lvert&{\color{cyan}{b_3}}\end{bmatrix}&\longrightarrow\begin{bmatrix}1&0&-1&-2&\lvert&{\color{cyan}{2b_1-b_2}}\\0&1&2&3&\lvert&{\color{cyan}{b_2-b_1}}\\0&0&0&0&\lvert&{\color{cyan}{-5b_1+b_2+b_3}}\end{bmatrix},\end{align*}$$

 which shows that for the system $\boxed{Ax = {\color{cyan}{b}}}$ to be consistent, we need ${\color{cyan}{-5b_1+b_2+b_3}}=0.$

In other words, we say that the vector ${\color{cyan}{b}}$ is in the

*   column space of the given matrix $A$, or
*   span of the columns of the given matrix $A$

if and only if  ${\color{cyan}{-5b_1+b_2+b_3}}=0.$ That is, the vector ${\color{cyan}{b}}$ can be generated as a linear combination $x_1a_2+x_2a_2+x_3a_3+x_4a_4$ if and only if ${\color{cyan}{-5b_1+b_2+b_3}}=0.$

---



---

For the matrices below, answer the following:


* number of variables,
* number of pivot variables,
* number of free variables,
* degrees of freedom for the soution to $Ax={\color{cyan}{0}},$
* write down the solution vector $x$ for $Ax={\color{cyan}{0}}$ clearly showing the degrees of freedom,
* are columns of $A$ linearly independent or dependent?
* what are the pivot columns?
* what are the free columns, if any?
* express the free columns, if any, in terms of the pivot columns.

$$\begin{align*}\begin{bmatrix}1&8&3\\-1&-6&-7\\1&2&15\\-1&-4&-11\end{bmatrix},\quad \begin{bmatrix}3&2\\1&-1\\4&0\\2&1\end{bmatrix},\quad \begin{bmatrix}1&-2&0&2\\1&1&3&-1\end{bmatrix}.\end{align*}$$

---



In [ ]:
# Type code here

Check whether the following systems of equations are consistent; if yes, then express the solution in vector form:

$$\begin{align*}(1)\,A &= \begin{bmatrix}1&8&3\\-1&-6&-7\\1&2&15\\-1&-4&-11\end{bmatrix},\ b = \begin{bmatrix}3\\2\\0\\1\end{bmatrix},\\\\(2)\,A &= \begin{bmatrix}1&8&3\\-1&-6&-7\\1&2&15\\-1&-4&-11\end{bmatrix},\ b = \begin{bmatrix}-3\\2\\0\\1\end{bmatrix},\\\\(3)\,A&=\begin{bmatrix}3&2\\1&-1\\4&0\\2&1\end{bmatrix},\ b = \begin{bmatrix}2\\-1\\1\\1\end{bmatrix},\\\\(4)\, A&=\begin{bmatrix}3&2\\1&-1\\4&0\\2&1\end{bmatrix},\ b = \begin{bmatrix}2\\-1\\0\\1\end{bmatrix},\\(5)\, A&=\begin{bmatrix}1&-2&0&2\\1&1&3&-1\end{bmatrix}, \ b = \begin{bmatrix}1\\2\end{bmatrix}.\end{align*}$$

---

In [ ]:
## Consider equation (4) above
# Augmented matrix
Ag = sp.Matrix([[3, 2, 2], [1, -1, -1], [4, 0, 0], [2, 1, 1]])

# Return the rref and the pivot column indices as a tuple
print(Ag.rref())

In [ ]:
## Consider equation (5) above
# Augmented matrix
Ag = sp.Matrix([[1, -2, 0, 2, 1], [1, 1, 3, -1, 2]])

# Return the rref and the pivot column indices as a tuple
print(Ag.rref())

In [ ]:
A = np.array([[1, -2, 0, 2], [1, 1, 3, -1]])
x3 = 1000
x4 = -1000

# Check null space solution (Ax = 0)
print(np.dot(A, x3*np.array([-2, -1, 1, 0])+x4*np.array([0, 1, 0, 1])))

# Check particular solution (Ax = b)
print(np.dot(A, np.array([5/3, 1/3, 0, 0])))

# Check full solution (Ax = b)
x = x3*np.array([-2, -1, 1, 0]) + x4*np.array([0, 1, 0, 1]) + np.array([5/3, 1/3, 0, 0])
print(np.dot(A, x))

---

Here, we simulate a patient dataset with 20 samples and 5 features (HR, BP, Temp, Height, Weight).

---

In [ ]:
# Simulate a sales dataset
#np.random.seed(100)
nsamples = 20
df = pd.DataFrame({'HR' : np.round(np.random.normal(loc = 76, scale = 8, size = nsamples)),
                   'BP' : np.round(np.random.normal(loc = 128, scale = 16, size = nsamples)),
                   'Temp' : np.round(np.random.normal(loc = 37, scale = 3, size = nsamples))})
df['Height'] = (1.1)*df['HR'] + (0.6)*df['BP'] + (0.25)*df['Temp']
df['Weight'] = (0.5)*df['HR'] + (0.25)*df['BP'] + (0.05)*df['Temp']
A = np.array(df)

---

What are the linearly independent features? Write the linearly dependent features, if any, in terms of the linearly independent features.

---

---

**Example**

---

In [ ]:
Ag = sp.Matrix(np.array([[1, 2, 1], [3, 4, 2], [5, 6, 0]]))
Ag.rref()



*   System is inconsistent.
*   Columns of $A$ are linearly independent.
*  What are the solutions to $Ax=0$? They are $x=\begin{bmatrix}0\\0\end{bmatrix} \Rightarrow N(A) = \left\{\begin{bmatrix}0\\0\end{bmatrix}\right\}.$
*  $C(A) = \left\{c_1\begin{bmatrix}1\\3\\5\end{bmatrix}+c_2\begin{bmatrix}2\\4\\6\end{bmatrix},\ c_1,c_2\in\mathbb{R}\right\} = \{c_1a_1+c_2a_2,\, c_1,c_2\in\mathbb{R}\}.$
* $\text{Rank}(A) = 2,$ which is also referred to as the $\text{dim}(C(A)),$ which is equal to the number of generators in the column space of $A,$ which is also equal to the number of pivot variables.
* $\text{Nullity}(A) = 0,$ which is also referred to as the $\text{dim}(N(A)),$ which is equal to the number of generators in the null space of $A,$ which is also equal to the number of free variables.


---

**Example**

---

In [ ]:
Ag = sp.Matrix(np.array([[1, 1, 1, 1, 1], [1, 2, 4, 8, 2], [1, 3, 9, 27, 3]]))
Ag.rref()



*   System is consistent.
*   Columns of $A$ are linearly dependent.
*  What are the solutions to $Ax=0$? They are, $x=\begin{bmatrix}x_1\\x_2\\x_3\\x_4\end{bmatrix} = \begin{bmatrix}-6x_4\\11x_4\\-6x_4\\x_4\end{bmatrix} = x_4\begin{bmatrix}-6\\11\\-6\\1\end{bmatrix}\Rightarrow N(A) = \left\{ x_4\begin{bmatrix}-6\\11\\-6\\1\end{bmatrix},\ x_4\in\mathbb{R}\right\}.$
* What are the solutions to $Ax=b$? They are, They are, $x=\begin{bmatrix}x_1\\x_2\\x_3\\x_4\end{bmatrix} = \begin{bmatrix}-6x_4\\11x_4+1\\-6x_4\\x_4\end{bmatrix} = x_4\begin{bmatrix}-6\\11\\-6\\1\end{bmatrix}+\begin{bmatrix}0\\1\\0\\0\end{bmatrix}= \left\{ x_4\begin{bmatrix}-6\\11\\-6\\1\end{bmatrix}+\begin{bmatrix}0\\1\\0\\0\end{bmatrix},\ x_4\in\mathbb{R}\right\}.$
*  $C(A) = \left\{c_1\begin{bmatrix}1\\1\\1\end{bmatrix}+c_2\begin{bmatrix}1\\2\\3\end{bmatrix}+c_3\begin{bmatrix}1\\4\\9\end{bmatrix},\ c_1,c_2,c_3\in\mathbb{R}\right\} = \{c_1a_1+c_2a_2+c_3a_3,\, c_1,c_2,c_3\in\mathbb{R}\}.$
* $\text{Rank}(A) = 3,$ which is also referred to as the $\text{dim}(C(A)),$ which is equal to the number of generators in the column space of $A,$ which is also equal to the number of pivot variables.
* $\text{Nullity}(A) = 1,$ which is also referred to as the $\text{dim}(N(A)),$ which is equal to the number of generators in the null space of $A,$ which is also equal to the number of free variables.
